import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "@next/font/local";

const poker = localFont({
  src: "../fonts/JqkasWild-w1YD6.ttf",
  variable: "--font-poker",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poker.className}>{children}</body>
    </html>
  );
}
